# -*- coding: utf-8 -*-
"""Data Injection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16hoMzRYB7iD0cRoz1_DhENAE-Kq5fjyY
"""

import pandas as pd

df = pd.read_csv('westcoast_original.csv')

#replaceing content
df.columns

counter = 0
extraction_limit = 2190
fake_values = []
for label, content in df.items():
  if(counter < extraction_limit):
    if(label == 'Wind speed at 100m (m/s)'):
      print("label: ", label)
      #print("Content: ", content, sep='\n')
      for i,items in enumerate(content):
        if(i < extraction_limit):
          fake_values.append(items)
print(fake_values)

import random
changed_indexes = []
number_of_times = 1 #number of times to inject, number_of_times*extraction_limit
current_index = 0 #current index of fake_values
start_index = 35040 - 8760 #start index 
for i in range(0, 1):
  current_counter = 0
  while(current_counter < extraction_limit):
    #injecting value
    injection_windspeed_value = fake_values[current_counter]
    #fetch current values in cells
    power = df.iat[start_index,1]
    direction = df.iat[start_index,2]
    temp = df.iat[start_index,4]
    pressure = df.iat[start_index,5]
    density = df.iat[start_index,6]
    print(injection_windspeed_value)
    #set values
    df.at[start_index, 'Wind speed at 100m (m/s)'] = injection_windspeed_value
    df.at[start_index, 'Power'] = power
    df.at[start_index, 'Wind direction at 100m (deg)'] = direction
    df.at[start_index, 'Air Temperature at 2m (k)'] = temp
    df.at[start_index, 'Surface air pressure (Pa)'] = pressure
    df.at[start_index, 'Density at hub height (kg/m^3)'] = density
    #df.set_value(start_index, 'Wind speed at 100m (m/s)',injection_windspeed_value)
    #df.set_value(start_index, 'Power',power)
    #df.set_value(start_index, 'Wind direction at 100m (deg)',direction)
    #df.set_value(start_index, 'Air Temperature at 2m (k)',temp)
    #df.set_value(start_index, 'Surface air pressure (Pa)',pressure)
    #df.set_value(start_index, 'Density at hub height (kg/m^3)',density)
    #increment counter
    current_counter = current_counter + 1 
    start_index = start_index + 1
    changed_indexes.append(start_index)

'''
  Only needed if the size of the extraction_limit is small
  #update counter to new start index
  remaining_size = 35040 - start_index
  remaining_bins = remaining_size / extraction_limit
  #generate random bin to start in
  random_bin = random.randint(1, int(remaining_bins))
  
  #new index to start at
  start_index = start_index + (random_bin * extraction_limit) '''



df.to_csv("injected_westcoast_25.csv", index=False)
